---
kind: pipeline
type: docker
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      username: fat0troll
      password:
        from_secret: registry_password
      repo: fat0troll/samba
      auto_tag: true
      when:
        branch:
          - master
        event:
          - push
          - tag